artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://githubusercontent.com
  local_data_file: artifacts/data_ingestion/winequality-red.csv
  unzip_dir: artifacts/data_ingestion
